services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    # platform: linux/x86_64 # only needed if running on Mac
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5

  backend:
    ## Remember to version lock! i.e use 1.0.0 instead of latest
    image: us-central1-docker.pkg.dev/rapidmcp-corp/mcp-apps/mcp-backend:1.0.0
    env_file: .env
    # platform: linux/x86_64 # only needed if running on Mac
    depends_on:
      db:
        condition: service_healthy

  web:
    ## Remember to version lock! i.e use 1.0.0 instead of latest
    image: us-central1-docker.pkg.dev/rapidmcp-corp/mcp-apps/web:1.0.
    env_file: .env
    command: sh -c "npm run db:migrate && node apps/web/server.js"
    # platform: linux/x86_64 # only needed if running on Mac
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    # platform: linux/x86_64 # only needed if running on Mac
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web
      - backend

volumes:
  db_data:
